bot:
  command_prefix: "!<"
  owner_discord_name: "baxterthehusky#1003"
  errors:
    message:
      prefix: "oopsie whoopsie~ a fucky wucky happened!"
  commands:
    help:
      protected: false
      protection_level: USER
    test:
      protected: true
      protection_level: OWNER

archive:
  message:
    limit: 1000000
