bot:
  command_prefix: "."
  owner_discord_name: "baxterthehusky#1003"
  guilds:
    mapping:
      directory: "guilds"
  errors:
    message:
      prefix: "oopsie whoopsie~ a fucky wucky happened!"
  commands:
  # Commands go here
   - name: default
     module: "src.commands.default.default"
     config: "src\\commands\\default\\config.yaml"
   - name: archive
     module: "src.commands.archive.commands"
     config: "src\\commands\\archive\\config.yaml"


archive:
  directory: "."
  dump:
    file_type: ".json"
  message:
    limit: 1000000
