bot:
  command_prefix: "!<"
  owner_discord_name: "baxterthehusky#1003"
  errors:
    message:
      prefix: "oopsie whoopsie~ a fucky wucky happened!"
  commands:
  # Commands go here
   - name: default
     module: "src.commands.default.default"
     config: "src\\commands\\default\\config.yaml"
   - name: dummy
     module: "src.commands.testing.dummy"
     config: "src\\commands\\testing\\config.yaml"

archive:
  message:
    limit: 1000000
