lolwut:
  function: lolwut
  protected: false
  protection_level: "USER"
pingme:
  function: ping_author
  protected: false
  protection_level: "USER"
channels:
  function: get_channels
  protected: false
  protection_level: "USER"
